# версия Docker Compose
version: '3.8'

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  db:
    image: postgres:14.3-alpine
    container_name: db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      #- TZ=Europe/Moscow

  server:
    build: shareit-server
    image: server
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/shareit
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      #- TZ=Europe/Moscow

  gateway:
    build: shareit-gateway
    image: gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_PORT=9090
      #- TZ=Europe/Moscow